version: 2
jobs:
  rubocop:
    docker:
      - image: cohenaj194/amazon_nmap_test
    steps:
      - checkout
      - run: 
          name: run rubocop
          command: |
            bundle install
            bundle exec rubocop
  rspec:
    docker:
      - image: cohenaj194/amazon_nmap_test
    environment:
      - AWS_ACCESS_KEY_ID: foobar
      - AWS_SECRET_ACCESS_KEY: foobar
    steps:
      - checkout
      - run: 
          name: run rspec
          command: |
            bundle install
            bundle exec rspec 
workflows:
  version: 2
  ruby_tests:
    jobs:
      - rspec
      - rubocop