Metrics/LineLength:
  Max: 400

Metrics/BlockLength:
  Max: 400

Metrics/MethodLength:
  Max: 400

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
