---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    - instance_id: "{{ lookup('env','SOURCE_INSTANCE_ID') }}"
    - subnet: "{{ lookup('env','SUBNET_ID') }}"
  tasks:
    - name: Shut down centos server
      ec2:
        instance_ids: '{{ instance_id }}'
        region: 'us-west-2'
        state: stopped
        wait: True
        vpc_subnet_id:  "{{ subnet }}"
  